# Generated by Django 4.0.4 on 2022-06-08 00:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brandID', models.AutoField(primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('planID', models.AutoField(primary_key=True, serialize=False)),
                ('planName', models.CharField(max_length=255)),
                ('amountOptions', models.CharField(max_length=128)),
                ('tentureOptions', models.CharField(max_length=128)),
                ('benefitPercentage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('benefitType', models.CharField(max_length=128)),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.brands')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('userEmail', models.CharField(max_length=255)),
                ('userPassword', models.CharField(max_length=255)),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promotionId', models.AutoField(primary_key=True, serialize=False)),
                ('limitedBy', models.CharField(max_length=64)),
                ('promotionValue', models.CharField(blank=True, max_length=255, null=True)),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.plans')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedAmount', models.CharField(max_length=255)),
                ('selectedTenture', models.CharField(max_length=255)),
                ('startedDate', models.DateTimeField(verbose_name='Start Date')),
                ('depositedAmount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('benefitPercentage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('benefitType', models.CharField(max_length=128)),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.brands')),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.plans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
        ),
    ]
